AUTOMOTIVE_PARTS = [
    "Engine Oil Filter",
    "Disc Brake Pad Set",
    "Disc Brake Rotor",
    "Air Filter",
    "Spark Plug",
    "Cabin Air Filter",
    "Serpentine Belt",
    "Vehicle Battery",
    "Wiper Blade",
    "Suspension Shock Absorber",
    "Automatic Transmission Fluid",
    "Disc Brake Caliper",
    "Engine Oil",
    "Suspension Stabilizer Bar Link",
    "Suspension Strut and Coil Spring Assembly",
    "Engine Coolant / Antifreeze",
    "Suspension Control Arm",
    "CV Axle Assembly",
    "Wheel Bearing and Hub Assembly",
    "Engine Valve Cover Gasket Set"
]

SEARCH_TERMS = {
    "Engine Oil Filter": "engine oil filter automotive car part",
    "Disc Brake Pad Set": "disc brake pad set automotive car",
    "Disc Brake Rotor": "disc brake rotor automotive car part",
    "Air Filter": "engine air filter automotive car",
    "Spark Plug": "spark plug automotive car engine",
    "Cabin Air Filter": "cabin air filter automotive car",
    "Serpentine Belt": "serpentine belt automotive car engine",
    "Vehicle Battery": "car battery automotive vehicle",
    "Wiper Blade": "windshield wiper blade automotive car",
    "Suspension Shock Absorber": "shock absorber suspension automotive car",
    "Automatic Transmission Fluid": "automatic transmission fluid automotive car",
    "Disc Brake Caliper": "disc brake caliper automotive car part",
    "Engine Oil": "engine oil automotive car motor oil",
    "Suspension Stabilizer Bar Link": "stabilizer bar link suspension automotive car",
    "Suspension Strut and Coil Spring Assembly": "strut coil spring assembly suspension automotive",
    "Engine Coolant / Antifreeze": "engine coolant antifreeze automotive car",
    "Suspension Control Arm": "control arm suspension automotive car",
    "CV Axle Assembly": "CV axle assembly automotive car part",
    "Wheel Bearing and Hub Assembly": "wheel bearing hub assembly automotive car",
    "Engine Valve Cover Gasket Set": "valve cover gasket set engine automotive"
}
