// Game data - automotive parts for PartsGuess MVP
const gameData = [
  {
    id: 1,
    image: "/parts-images/engine_oil_filter.jpg",
    correctAnswer: "Engine Oil Filter",
    options: ['Engine Oil Filter', 'Fuel Filter', 'Air Filter', 'Transmission Filter'],
    description: "Removes contaminants from engine oil to keep the engine running smoothly and extend its life.",
  },
  {
    id: 2,
    image: "/parts-images/disc_brake_pad_set.jpg",
    correctAnswer: "Disc Brake Pad Set",
    options: ['Disc Brake Pad Set', 'Drum Brake Shoes', 'Brake Rotors', 'Brake Calipers'],
    description: "Friction material that presses against brake rotors to slow down or stop the vehicle.",
  },
  {
    id: 3,
    image: "/parts-images/disc_brake_rotor.jpg",
    correctAnswer: "Disc Brake Rotor",
    options: ['Disc Brake Rotor', 'Brake Drum', 'Flywheel', 'Clutch Disc'],
    description: "Metal disc that brake pads clamp down on to create friction and stop the vehicle.",
  },
  {
    id: 4,
    image: "/parts-images/air_filter.jpg",
    correctAnswer: "Air Filter",
    options: ['Air Filter', 'Cabin Air Filter', 'Oil Filter', 'Fuel Filter'],
    description: "Filters air entering the engine to prevent dirt and debris from causing damage.",
  },
  {
    id: 5,
    image: "/parts-images/spark_plug.jpg",
    correctAnswer: "Spark Plug",
    options: ['Spark Plug', 'Glow Plug', 'Ignition Coil', 'Fuel Injector'],
    description: "Ignites the air-fuel mixture in the engine's combustion chamber to power the vehicle.",
  },
  {
    id: 6,
    image: "/parts-images/cabin_air_filter.jpg",
    correctAnswer: "Cabin Air Filter",
    options: ['Cabin Air Filter', 'Engine Air Filter', 'HVAC Filter', 'Oil Filter'],
    description: "Filters air entering the passenger compartment through the HVAC system.",
  },
  {
    id: 7,
    image: "/parts-images/serpentine_belt.jpg",
    correctAnswer: "Serpentine Belt",
    options: ['Serpentine Belt', 'Timing Belt', 'V-Belt', 'Drive Chain'],
    description: "Single belt that drives multiple engine accessories like the alternator, power steering, and A/C.",
  },
  {
    id: 8,
    image: "/parts-images/vehicle_battery.jpg",
    correctAnswer: "Vehicle Battery",
    options: ['Vehicle Battery', 'Alternator', 'Starter Motor', 'Capacitor'],
    description: "Provides electrical power to start the engine and run electrical systems when the engine is off.",
  },
  {
    id: 9,
    image: "/parts-images/wiper_blade.jpg",
    correctAnswer: "Wiper Blade",
    options: ['Wiper Blade', 'Wiper Motor', 'Wiper Arm', 'Windshield Washer Pump'],
    description: "Rubber blade that clears water and debris from the windshield for clear visibility.",
  },
  {
    id: 10,
    image: "/parts-images/suspension_shock_absorber.jpg",
    correctAnswer: "Suspension Shock Absorber",
    options: ['Suspension Shock Absorber', 'Coil Spring', 'Strut Mount', 'Sway Bar'],
    description: "Dampens suspension movement to provide a smooth ride and maintain tire contact with the road.",
  },
  {
    id: 11,
    image: "/parts-images/automatic_transmission_fluid.jpg",
    correctAnswer: "Automatic Transmission Fluid",
    options: ['Automatic Transmission Fluid', 'Engine Oil', 'Power Steering Fluid', 'Brake Fluid'],
    description: "Lubricates and cools automatic transmission components while enabling gear changes.",
  },
  {
    id: 12,
    image: "/parts-images/disc_brake_caliper.jpg",
    correctAnswer: "Disc Brake Caliper",
    options: ['Disc Brake Caliper', 'Brake Master Cylinder', 'Brake Booster', 'ABS Module'],
    description: "Houses brake pads and uses hydraulic pressure to squeeze them against the brake rotor.",
  },
  {
    id: 13,
    image: "/parts-images/engine_oil.jpg",
    correctAnswer: "Engine Oil",
    options: ['Engine Oil', 'Transmission Fluid', 'Coolant', 'Power Steering Fluid'],
    description: "Lubricates engine components, reduces friction, and helps regulate engine temperature.",
  },
  {
    id: 14,
    image: "/parts-images/suspension_stabilizer_bar_link.jpg",
    correctAnswer: "Suspension Stabilizer Bar Link",
    options: ['Suspension Stabilizer Bar Link', 'Tie Rod End', 'Ball Joint', 'Control Arm Bushing'],
    description: "Connects the stabilizer bar to the suspension to reduce body roll during cornering.",
  },
  {
    id: 15,
    image: "/parts-images/suspension_strut_and_coil_spring_assembly.jpg",
    correctAnswer: "Suspension Strut and Coil Spring Assembly",
    options: ['Suspension Strut and Coil Spring Assembly', 'Shock Absorber', 'Leaf Spring', 'Torsion Bar'],
    description: "Complete suspension unit that supports vehicle weight and absorbs road impacts.",
  },
  {
    id: 16,
    image: "/parts-images/engine_coolant___antifreeze.jpg",
    correctAnswer: "Engine Coolant / Antifreeze",
    options: ['Engine Coolant / Antifreeze', 'Engine Oil', 'Transmission Fluid', 'Windshield Washer Fluid'],
    description: "Liquid that circulates through the engine to regulate temperature and prevent freezing.",
  },
  {
    id: 17,
    image: "/parts-images/suspension_control_arm.jpg",
    correctAnswer: "Suspension Control Arm",
    options: ['Suspension Control Arm', 'Tie Rod', 'Sway Bar', 'Strut Assembly'],
    description: "Connects the wheel hub to the vehicle frame and allows controlled wheel movement.",
  },
  {
    id: 18,
    image: "/parts-images/cv_axle_assembly.jpg",
    correctAnswer: "CV Axle Assembly",
    options: ['CV Axle Assembly', 'Drive Shaft', 'Axle Shaft', 'Universal Joint'],
    description: "Transfers power from the transmission to the wheels while allowing for steering and suspension movement.",
  },
  {
    id: 19,
    image: "/parts-images/wheel_bearing_and_hub_assembly.jpg",
    correctAnswer: "Wheel Bearing and Hub Assembly",
    options: ['Wheel Bearing and Hub Assembly', 'Brake Hub', 'Wheel Stud', 'Lug Nut'],
    description: "Allows wheels to rotate smoothly while supporting the vehicle's weight.",
  },
  {
    id: 20,
    image: "/parts-images/engine_valve_cover_gasket_set.jpg",
    correctAnswer: "Engine Valve Cover Gasket Set",
    options: ['Engine Valve Cover Gasket Set', 'Head Gasket', 'Oil Pan Gasket', 'Intake Manifold Gasket'],
    description: "Seals the valve cover to prevent oil leaks from the top of the engine.",
  },
]
